controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - base_rotation
      - rot1
      - rot3
      - rot6
      - rot7
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: home